org: mtamayoh
service: api-s3

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  stage: ${opt:stage, 'dev'}  # Usa 'dev' por defecto si no se pasa otro
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::682419757205:role/LabRole

  environment:
    STAGE: ${self:provider.stage}
    BUCKET_PREFIX: "api-s3-${self:provider.stage}"

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 1024
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true

  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true

  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: /s3/crear-bucket
          method: post
          cors: true

  crear_directorio:
    handler: crear_directorio.lambda_handler
    events:
      - http:
          path: /s3/crear-directorio
          method: post
          cors: true

  subir_archivo:
    handler: subir_archivo.lambda_handler
    memorySize: 1024
    timeout: 30
    events:
      - http:
          path: /s3/subir-archivo
          method: post
          cors: true

