org: mtamayoh
service: api-s3

provider:
  name: aws
  runtime: python3.13
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::682419757205:role/LabRole

functions:
  # Lista todos los buckets
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 1024
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda

  # Lista los objetos de un bucket
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda

  # ðŸ†• Crea un nuevo bucket
  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: /s3/crear-bucket
          method: post
          cors: true
          integration: lambda

  # ðŸ†• Crea un nuevo directorio en un bucket existente
  crear_directorio:
    handler: crear_directorio.lambda_handler
    events:
      - http:
          path: /s3/crear-directorio
          method: post
          cors: true
          integration: lambda

  # ðŸ†• Sube un archivo a un directorio de un bucket existente
  subir_archivo:
    handler: subir_archivo.lambda_handler
    memorySize: 1024
    timeout: 30
    events:
      - http:
          path: /s3/subir-archivo
          method: post
          cors: true
          integration: lambda
